[project]
name = "attempt"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "loguru>=0.7.3",
]

[dependency-groups]
dev = [
    "ruff>=0.12.11",
]
